# True Colors Support
set -g default-terminal "tmux-256color"
set -sg terminal-overrides "*:RGB"

# Prefix change
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# General
set -g mouse on
set -g escape-time 0
set -g set-clipboard on
set -g allow-passthrough on
set -g history-limit 5000
set -g focus-events on
set -g display-time 4000
set -g aggressive-resize on

# Resize Panes
bind -r Left resize-pane -L 5
bind -r Right resize-pane -R 5
bind -r Up resize-pane -U 5
bind -r Down resize-pane -D 5

# Color Theme, requires a theme file ot be sourced before
#source ~/.config/tmux/themes/catppuccin.conf
source ~/.config/tmux/themes/rose-pine.conf

# Status bar
set -g status-position top
set -g status-interval 3
set -g status-left-length 100
set -g status-right-length 150
set -g status-style "fg=#{@thm_fg},bg=default"
set -g status-left "#{?client_prefix,#[fg=#{@thm_prefix}],#[fg=#{@thm_warm}]}#[bold] #S #[fg=#{@thm_muted},nobold] | "
set -g window-status-current-format "#[fg=#{@thm_accent},bold]  #[underscore]#I:#W#[nounderscore]#{?window_zoomed_flag,#[fg=#{@thm_warn}] 󰍋 #[fg=#{@thm_accent}],}"
set -g window-status-bell-style "fg=#{@thm_alert},bg=default,none"
set -g window-status-format "#{?window_bell_flag,#[fg=#{@thm_alert}] ,#[fg=#{@thm_muted}] }#I:#W"
set -g status-right "#[fg=#{@thm_fg}]  #{pane_current_path} #[fg=#{@thm_muted}]| #[fg=#{@thm_cool}]󰒋 #h "
set -g message-style "fg=#{@thm_accent},bg=default"
set -g mode-style "fg=#{@thm_bg},bg=#{@thm_accent}"
set -g pane-border-style "fg=#{@thm_muted}"
set -g pane-active-border-style "fg=#{@thm_accent}"

# Windows and panes start at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on
set -g monitor-bell on

# Vim-like copy/paste
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# Navigate Panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Split windows, split in current directory
bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"


bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded"
